name: wts_support_engineer
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#................after update version code ,need to run flutter build apk.............
version: 1.0.3+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^2.1.0

  transparent_image: ^2.0.0
  flutter_spinkit: ^5.0.0
  get: ^3.26.0
  image_picker: ^0.8.1+3
  image_cropper: ^1.4.1
  fluttertoast: ^8.0.7
  #  firebase_core: any
  #  firebase_auth: ^0.18.1+2
  cloud_firestore: ^2.4.0
  #    # ...........................fcm source...........................
  #    #https://github.com/Amanullahgit/FCM_Flutter-Notification
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^8.0.0
  #  flutter_local_notifications: ^3.0.1+7
  #  firebase_storage: ^4.0.1
  animated_text_kit: ^4.2.1
  auto_size_text: ^2.1.0
  http: ^0.13.3
  #....................retrofit.................
  retrofit: ^2.0.0
  dio: ^4.0.0
  built_value: any
  json_annotation: any
  logger: ^1.0.0
  built_value_generator: any
  #.................network image........
  cached_network_image: ^3.0.0
  loading_overlay: ^0.2.1
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  # chopper.........
  chopper: ^3.0.6

  # Remote API
  connectivity: ^3.0.3
  # Remote API
  data_connection_checker: ^0.3.4
  flutter_swiper: ^1.1.6
  carousel_slider: ^4.0.0
  font_awesome_flutter: ^9.1.0
  flutter_search_bar: ^2.1.0
  path_provider: ^2.0.2
  modal_bottom_sheet: ^2.0.0
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.9
  pie_chart: ^5.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #....................chopper.................
  build_runner: any
  json_serializable: any
  mockito: ^5.0.5
  chopper_generator: ^3.0.6
  flutter_launcher_icons: ^0.9.2


  #generate: true
  #command: flutter pub run flutter_launcher_icons:main
#flutter_icons:
#  image_path: "assets/launcher.png"
#  android: true
#  ios: true

dependency_overrides:
  analyzer: ^1.7.1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages